<!DOCTYPE html>
<html>
<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="utf-8">
  

  
  <title>CERT C++编码规范翻译（ERR） | MathxH</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="异常和错误处理ERR50-CPP. 不要突然的终止程序严重程度: 低。 允许程序在运行中非正常终止会导致一些资源没有被释放，容易遭受服务拒绝攻击。 std::abort(),std::quick_exit()和std::_Exit()函数通常用来快速突然的终止程序运行。一旦它们被调用，那么是不会调用std::atexit()函数注册的exit handler的，也不会自动调用程序中各类对象的析构函">
<meta name="keywords" content="CERT,C&#x2F;C++">
<meta property="og:type" content="article">
<meta property="og:title" content="CERT C++编码规范翻译（ERR）">
<meta property="og:url" content="https://alexiachen.github.io/blog/2017/08/09/cert-cpp-seven/index.html">
<meta property="og:site_name" content="MathxH">
<meta property="og:description" content="异常和错误处理ERR50-CPP. 不要突然的终止程序严重程度: 低。 允许程序在运行中非正常终止会导致一些资源没有被释放，容易遭受服务拒绝攻击。 std::abort(),std::quick_exit()和std::_Exit()函数通常用来快速突然的终止程序运行。一旦它们被调用，那么是不会调用std::atexit()函数注册的exit handler的，也不会自动调用程序中各类对象的析构函">
<meta property="og:locale" content="en">
<meta property="og:updated_time" content="2019-01-04T15:05:55.855Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="CERT C++编码规范翻译（ERR）">
<meta name="twitter:description" content="异常和错误处理ERR50-CPP. 不要突然的终止程序严重程度: 低。 允许程序在运行中非正常终止会导致一些资源没有被释放，容易遭受服务拒绝攻击。 std::abort(),std::quick_exit()和std::_Exit()函数通常用来快速突然的终止程序运行。一旦它们被调用，那么是不会调用std::atexit()函数注册的exit handler的，也不会自动调用程序中各类对象的析构函">
  
    <link rel="alternate" href="/blog/atom.xml" title="MathxH" type="application/atom+xml">
  
  
    <link rel="icon" href="/favicon.png">
  
  
    <link href="//fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  
  <link rel="stylesheet" href="/blog/css/style.css">
</head>
</html>
<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/blog/" id="logo">MathxH</a>
      </h1>
      
        <h2 id="subtitle-wrap">
          <a href="/blog/" id="subtitle">MathxH</a>
        </h2>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/blog/">Home</a>
        
          <a class="main-nav-link" href="/blog/archives">Archives</a>
        
          <a class="main-nav-link" href="/blog/about">About</a>
        
          <a class="main-nav-link" href="/blog/resume">Resume</a>
        
      </nav>
      <nav id="sub-nav">
        <a></a>
        
          <a id="nav-rss-link" class="nav-icon" href="/blog/atom.xml" title="RSS Feed"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="Search"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="https://alexiachen.github.io/blog"></form>
      </div>
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-cert-cpp-seven" class="article article-type-post" itemscope="" itemprop="blogPost">
  <div class="article-meta">
    <a href="/blog/2017/08/09/cert-cpp-seven/" class="article-date">
  <time datetime="2017-08-09T02:32:21.000Z" itemprop="datePublished">2017-08-09</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      CERT C++编码规范翻译（ERR）
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <h2 id="异常和错误处理"><a href="#异常和错误处理" class="headerlink" title="异常和错误处理"></a>异常和错误处理</h2><h3 id="ERR50-CPP-不要突然的终止程序"><a href="#ERR50-CPP-不要突然的终止程序" class="headerlink" title="ERR50-CPP. 不要突然的终止程序"></a>ERR50-CPP. 不要突然的终止程序</h3><p>严重程度: 低。 允许程序在运行中非正常终止会导致一些资源没有被释放，容易遭受服务拒绝攻击。</p>
<p>std::abort(),std::quick_exit()和std::_Exit()函数通常用来快速突然的终止程序运行。一旦它们被调用，那么是不会调用std::atexit()函数注册的exit handler的，也不会自动调用程序中各类对象的析构函数，线程对象的析构函数也不会被调用，还有网络socket连接等等资源。程序的扫尾工作不可能进行。</p>
<p>std::terminate()函数调用terminate_handler函数，该handler函数默认调用std::abort()函数。</p>
<p>C++标准定义了std::termiate()函数可能在以下几种情况被间接调用:</p>
<ul>
<li><p>When the exception handling mechanism, after completing the initialization of the exception object but before activation of a handler for the exception, calls a function that exits via an exception ([except.throw], paragraph 7)</p>
</li>
<li><p>When a throw-expression with no operand attempts to rethrow an exception and no<br>exception is being handled ([except.throw], paragraph 9)</p>
</li>
<li><p>When the exception handling mechanism cannot find a handler for a thrown exception<br>([except.handle], paragraph 9)</p>
</li>
<li><p>When the search for a handler encounters the outermost block of a function with a noexceptspecification that does not allow the exception ([except.spec], paragraph 9)</p>
</li>
<li><p>When the destruction of an object during stack unwinding terminates by throwing an<br>exception ([except.ctor], paragraph 3)</p>
</li>
<li><p>When initialization of a nonlocal variable with static or thread storage duration exits via an exception ([basic.start.init], paragraph 6)</p>
</li>
<li><p>When destruction of an object with static or thread storage duration exits via an exception ([basic.start.term], paragraph 1)</p>
</li>
<li><p>When execution of a function registered with std::atexit() or std::at_quick_exit() exits via an exception ([support.start.term], paragraphs 8 and 12)</p>
</li>
<li><p>When the implementation’s default unexpected exception handler is called ([except.unexpected], paragraph 2) Note that std::unexpected() is currently deprecated.</p>
</li>
<li><p>When std::unexpected() throws an exception that is not allowed by the previously violated dynamic-exception-specification, and std::bad_exception() is not included in that dynamic-exception-specification ([except.unexpected], paragraph 3)</p>
</li>
<li><p>When the function std::nested_exception::rethrow_nested() is called for an object that has captured no exception ([except.nested], paragraph 4)</p>
</li>
<li><p>When execution of the initial function of a thread exits via an exception ([thread.thread.constr], paragraph 5)</p>
</li>
<li><p>When the destructor is invoked on an object of type std::thread that refers to a joinable thread ([thread.thread.destr], paragraph 1)</p>
</li>
<li><p>When the copy assignment operator is invoked on an object of type std::thread that refers to a joinable thread ([thread.thread.assign], paragraph 1)</p>
</li>
<li><p>When calling condition_variable::wait(), condition_variable::wait_until(), or condition_variable::wait_for() results in a failure to meet the postcondition: lock.owns_lock() == true or lock.mutex() is not locked by the calling thread ([thread.condition.condvar], paragraphs 11, 16, 21, 28, 33, and 40)</p>
</li>
<li><p>When calling condition_variable_any::wait(), condition_variable_any::wait_until(), or condition_variable_any::wait_for() results in a failure to meet the postcondition: lock is not locked by the calling thread ([thread.condition.condvarany], paragraphs 11, 16, and 22)</p>
</li>
</ul>
<p>所以在以上那么多场景下，隐式调用std::terminate()直接导致调用栈不能收缩，C++标准[except.terminate]有如下声明:</p>
<blockquote>
<p>In the situation where no matching handler is found, it is implementation-defined whether or not the stack is unwound before std::terminate() is called. In the situation where the search for a handler encounters the outermost block of a function with a noexcept-specification that does not allow the exception, it is implementation-defined whether the stack is unwound, unwound partially, or not unwound at all before std::terminate() is called. In all other situations, the stack shall not be unwound before std::terminate() is called.</p>
</blockquote>
<p>不要显式或隐式调用std::quick_exit(),std::abort()和std::_Exit()。当然，在恰当的情况下可以调用std::exit()来终止程序，因为该函数的调用，会安全的执行程序运行中各类对象的析构函数和恰当的清理释放资源。</p>
<h4 id="代码样例对比"><a href="#代码样例对比" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstdlib&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123; <span class="comment">// Not invoked by the program except as an exit handler.</span></span><br><span class="line">  throwing_func();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">if</span> (<span class="number">0</span> != <span class="built_in">std</span>::atexit(f)) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码显然有问题，因为在exit handler函数中不小心调用了可能会抛出异常的函数，那么会间接导致std::terminate()调用。所以要阻止异常向exit handler函数外抛出:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstdlib&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123; <span class="comment">// Not invoked by the program except as an exit handler.</span></span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    throwing_func();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">if</span> (<span class="number">0</span> != <span class="built_in">std</span>::atexit(f)) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>当然，如果程序发生不可能恢复的错误的时候，可以用std::abort,std::_Exit和std::terminate </p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">report</span><span class="params">(<span class="keyword">const</span> <span class="keyword">char</span> *msg)</span> <span class="keyword">noexcept</span></span>;</span><br><span class="line"></span><br><span class="line">[[noreturn]] <span class="function"><span class="keyword">void</span> <span class="title">fast_fail</span><span class="params">(<span class="keyword">const</span> <span class="keyword">char</span> *msg)</span> </span>&#123;</span><br><span class="line">  <span class="comment">// Report error message to operator</span></span><br><span class="line">  report(msg);</span><br><span class="line">  <span class="comment">// Terminate</span></span><br><span class="line">  <span class="built_in">std</span>::terminate();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">critical_function_that_fails</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    critical_function_that_fails();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    fast_fail(<span class="string">"Critical function failure"</span>);</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="ERR51-CPP-处理所有的异常"><a href="#ERR51-CPP-处理所有的异常" class="headerlink" title="ERR51-CPP. 处理所有的异常"></a>ERR51-CPP. 处理所有的异常</h3><blockquote>
<p><em>首先这个条款我持有保留意见，不应该catch所有异常，有一些异常是开发者自身的编码原因导致的，比如容器越界等，如果catch住这类异常反而让程序继续运行，在错误的道路上越走越远，不好调试分析，不如立刻让它崩溃，还可以通过coredump查看现场原因。可能是CERT C++的规范偏向于软件安全方面的考量吧</em></p>
</blockquote>
<p>严重程度：低。允许程序非正常终止会导致资源不能及时释放，关闭。容易遭受拒绝服务攻击。</p>
<p>当一个异常被抛出，那么异常会试图匹配“离它最近的”处理代码块(handler)，handler也就是try catch块，如果没有匹配的handler，那么异常会一直往调用栈的上层抛出，直到main函数或者线程的入口函数，如果还没有匹配的handler，那么结果就会如C++标准[except.handler]所描述的那样,runtime库直接自动调用std::terminate()终止程序:</p>
<blockquote>
<p>If no matching handler is found, the function std::terminate() is called; whether or not the stack is unwound before this call to std::terminate() is implementationdefined.</p>
</blockquote>
<p>危害显而易见了，由于直接非正常终止程序，那么程序中的对象都不会调用析构函数，程序的外部依赖资源（Socket连接，文件句柄）都来不及释放，这样就不符合ERR50-CPP的规范。</p>
<h4 id="代码样例对比-1"><a href="#代码样例对比-1" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  throwing_func();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  f();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码可能会抛出异常，但是没有匹配的try catch代码块(handler)，所以最终std::terminate()被调用，程序非正常终止，应该改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  throwing_func();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    f();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>异常处理应该终止于main函数内，不能再向main函数外抛了。这样调用栈才来得及收缩到main上。这样也方便管理资源。</p>
<h4 id="代码样例对比-2"><a href="#代码样例对比-2" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;thread&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">thread_start</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  throwing_func();</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="built_in">std</span>::<span class="function">thread <span class="title">t</span><span class="params">(thread_start)</span></span>;</span><br><span class="line">  t.join();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码显然有问题，因为main函数的本质也是一个线程入口函数，只不过是主线程入口函数而已。所以说，以上的代码的异常没有在线程入口函数内被就阻止，还会继续往外抛，那么线程函数就被非正常终止了，最终又会调用std::terminate()。所以在线程入口函数内就要catch住异常:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;thread&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">throwing_func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">thread_start</span><span class="params">(<span class="keyword">void</span>)</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    throwing_func();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125; </span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="built_in">std</span>::<span class="function">thread <span class="title">t</span><span class="params">(thread_start)</span></span>;</span><br><span class="line">  t.join();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="ERR52-CPP-不要使用setjmp-或longjmp-函数"><a href="#ERR52-CPP-不要使用setjmp-或longjmp-函数" class="headerlink" title="ERR52-CPP. 不要使用setjmp()或longjmp()函数"></a>ERR52-CPP. 不要使用setjmp()或longjmp()函数</h3><p>严重程度: 低。 使用这两个函数非常容易造成资源没有按预料中的被销毁，这样就容易遭受服务拒绝攻击。</p>
<p>C语言标准库提供的setjmp()和longjmp()函数可以用来模拟异常的throw和catch机制，然而这样在内存中的跳转，会很容易忽略遗忘的资源释放，造成未定义行为。这样资源泄漏就导致容易遭受服务拒绝攻击。</p>
<p>C++标准[support.runtime]作出了以下声明:</p>
<blockquote>
<p>The function signature longjmp(jmp_buf jbuf, int val) has more restricted behavior in this International Standard. A setjmp/longjmp call pair has undefined behavior if replacing the setjmp and longjmp by catch and throw would invoke any non-trivial destructors for any automatic objects.</p>
</blockquote>
<p>所以，如果用C++，那么就使用try catch来代替这两个函数吧。</p>
<h4 id="代码样例对比-3"><a href="#代码样例对比-3" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;csetjmp&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="keyword">static</span> jmp_buf env;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">Counter</span> &#123;</span></span><br><span class="line">  <span class="keyword">static</span> <span class="keyword">int</span> instances;</span><br><span class="line">  Counter() &#123; ++instances; &#125;</span><br><span class="line">  ~Counter() &#123; --instances; &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="keyword">int</span> Counter::instances = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  Counter c;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"f(): Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  <span class="built_in">std</span>::longjmp(env, <span class="number">1</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"Before setjmp(): Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  <span class="keyword">if</span> (setjmp(env) == <span class="number">0</span>) &#123;</span><br><span class="line">    f();</span><br><span class="line">  &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"From longjmp(): Instances: "</span></span><br><span class="line">              &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"After longjmp(): Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>这段代码有相当严重的问题，会直接造成未定义行为。因为f()中的局部对象c可能由于longjump跳转没有调用它的析构函数而造成严重问题。</p>
<p>以下讨论下Clang 3.8在Linux下运行这段代码，输出是:</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Before setjmp(): Instances: 0</span><br><span class="line">f(): Instances: 1</span><br><span class="line">From longjmp(): Instances: 1</span><br><span class="line">After longjmp(): Instances: 1</span><br></pre></td></tr></table></figure>
<p>以上代码就如分析的那样，没有调用对象c的析构函数，当然，也可能会调用析构函数，因为行为是未定义的。所以应该用try catch代替:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">Counter</span> &#123;</span></span><br><span class="line">  <span class="keyword">static</span> <span class="keyword">int</span> instances;</span><br><span class="line">  Counter() &#123; ++instances; &#125;</span><br><span class="line">  ~Counter() &#123; --instances; &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="keyword">int</span> Counter::instances = <span class="number">0</span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  Counter c;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"f(): Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  <span class="keyword">throw</span> <span class="string">"Exception"</span>;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"Before throw: Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    f();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (<span class="keyword">const</span> <span class="keyword">char</span> *E) &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"From catch: Instances: "</span></span><br><span class="line">              &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  </span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; <span class="string">"After catch: Instances: "</span></span><br><span class="line">            &lt;&lt; Counter::instances &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码以抛异常处理异常的方式来实现，这样到了catch块中，局部对象c的析构函数就能如预料中那样被调用了，不会造成未定义行为，以下是Clang 3.8在Linux上的输出以证明此观点:</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Before throw: Instances: 0</span><br><span class="line">f(): Instances: 1</span><br><span class="line">From catch: Instances: 0</span><br><span class="line">After catch: Instances: 0</span><br></pre></td></tr></table></figure>
<h3 id="ERR53-CPP-在构造函数和析构函数中不要在function-try-block-handler中引用基类或者类的数据成员"><a href="#ERR53-CPP-在构造函数和析构函数中不要在function-try-block-handler中引用基类或者类的数据成员" class="headerlink" title="ERR53-CPP. 在构造函数和析构函数中不要在function-try-block handler中引用基类或者类的数据成员"></a>ERR53-CPP. 在构造函数和析构函数中不要在function-try-block handler中引用基类或者类的数据成员</h3><p>严重程度: 低。在构造函数异常handler或者析构函数异常handler中访问非静态数据会导致未定义行为。</p>
<p>C++标准[except.handle]有如下声明:</p>
<blockquote>
<p>Referring to any non-static member or base class of an object in the handler for a function-try-block of a constructor or destructor for that object results in undefined behavior</p>
</blockquote>
<h4 id="代码样例对比-4"><a href="#代码样例对比-4" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">C</span> &#123;</span></span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">string</span> str;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  C(<span class="keyword">const</span> <span class="built_in">std</span>::<span class="built_in">string</span> &amp;s) <span class="keyword">try</span> : str(s) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="keyword">if</span> (!str.empty()) &#123;</span><br><span class="line">       <span class="comment">// ...</span></span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码构造函数采用了function-try-block的形式来处理异常，然而在其中直接引用了str成员对象，造成未定义行为。需要改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">C</span> &#123;</span></span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">string</span> str;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  C(<span class="keyword">const</span> <span class="built_in">std</span>::<span class="built_in">string</span> &amp;s) <span class="keyword">try</span> : str(s) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="keyword">if</span> (!s.empty()) &#123; <span class="comment">//注意，这里是构造函数的参数s，不是成员对象str</span></span><br><span class="line">       <span class="comment">// ...</span></span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码就完美避免产生未定义行为了。</p>
<h3 id="ERR54-CPP-catch-handler的参数类型应该采用从most-derived到least-derived的优先级顺序考虑，从低到高。"><a href="#ERR54-CPP-catch-handler的参数类型应该采用从most-derived到least-derived的优先级顺序考虑，从低到高。" class="headerlink" title="ERR54-CPP. catch handler的参数类型应该采用从most derived到least derived的优先级顺序考虑，从低到高。"></a>ERR54-CPP. catch handler的参数类型应该采用从most derived到least derived的优先级顺序考虑，从低到高。</h3><p>严重程度: 中等。当自定义的异常发生如果catch打乱了异常优先级，那么会造成无法预料程序控制流混乱。</p>
<p>一般来说，所有自定义的异常或者预定义的异常都必须继承同一个基类(std::exception)，这样形成一个继承链，most derived的异常一般就是直接继承std::exception的类，least derived的异常就是离std::exception继承“最远”的类。</p>
<h4 id="代码样例对比-5"><a href="#代码样例对比-5" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="comment">// Classes used for exception handling</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">B</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">D</span> :</span> <span class="keyword">public</span> B &#123;&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (B &amp;b) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (D &amp;d) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码自定义了两个异常类，B和D。但是catch handler却考虑优先处理B，而不是D，而D的父亲却是B，所以catch(D&amp; d)的代码块永远不会被执行，因为如果抛出D类型的异常全部被匹配到catch(B &amp;b)的代码块了，所以要有限匹配小范围的异常:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="comment">// Classes used for exception handling</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">B</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">D</span> :</span> <span class="keyword">public</span> B &#123;&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (D &amp;d) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (B &amp;b) &#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码无论抛出什么类型的异常都可以匹配到期待的catch代码块了。</p>
<h3 id="ERR55-CPP-遵循异常规范"><a href="#ERR55-CPP-遵循异常规范" class="headerlink" title="ERR55-CPP. 遵循异常规范"></a>ERR55-CPP. 遵循异常规范</h3><p>严重程度: 低。 抛出一个未确定的异常导致打断控制流，容易造成程序终止和拒绝服务攻击。</p>
<p>C++标准[except.spec]有如下声明:</p>
<blockquote>
<p>A function is said to allow an exception of type E if the constant-expression in its noexcept-specification evaluates to false or its dynamic-exception-specification contains a type T for which a handler of type T would be a match (15.3) for an exception of type E.</p>
</blockquote>
<p>如果一个函数没遵循异常规范并抛出一个异常，那么直接会导致implementation-defined类型的程序终止。</p>
<p>如果一个函数声明了一个动态异常规范但是又抛出了一个不遵守规范的异常，那么会导致函数std::unexpected()被调用，当然，这个函数的行为可以被覆盖，但是默认情况下会导致一个std::bad_exception()的异常被抛出，除非在异常规范里面列出了std::bad_exception()，不然，std::terminate()就会被间接调用。</p>
<p>所以要严格遵守异常规范。</p>
<h4 id="代码样例对比-6"><a href="#代码样例对比-6" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception1</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception2</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">foo</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">throw</span> Exception2&#123;&#125;;</span><br><span class="line">  <span class="comment">// Okay because foo() promises nothing about exceptions</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">bar</span><span class="params">()</span> <span class="title">throw</span> <span class="params">(Exception1)</span> </span>&#123;</span><br><span class="line">  foo();</span><br><span class="line">  <span class="comment">// Bad because foo() can throw Exception2</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码中，函数bar()明显声明了只能抛出Exception1的异常规范，但是bar()函数却因为调用foo()函数可能会抛出Exception2的异常，所以是错的，会导致程序不正常终止，应该改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception1</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception2</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">foo</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">throw</span> Exception2&#123;&#125;;</span><br><span class="line">  <span class="comment">// Okay because foo() promises nothing about exceptions</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">bar</span><span class="params">()</span> <span class="title">throw</span> <span class="params">(Exception1)</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    foo();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (Exception2 e) &#123;</span><br><span class="line">    <span class="comment">// Handle error without rethrowing it</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码让Exception2的异常终止于bar()函数内部，不再让其往外抛出，这样就是正确的代码了。或者可以改成以下，新增一个异常在动态异常规范中:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception1</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Exception2</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">foo</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">throw</span> Exception2&#123;&#125;;</span><br><span class="line">  <span class="comment">// Okay because foo() promises nothing about exceptions</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">bar</span><span class="params">()</span> <span class="title">throw</span> <span class="params">(Exception1, Exception2)</span> </span>&#123;</span><br><span class="line">  foo();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h4 id="代码样例对比-7"><a href="#代码样例对比-7" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstddef&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;vector&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">(<span class="built_in">std</span>::<span class="built_in">vector</span>&lt;<span class="keyword">int</span>&gt; &amp;v, <span class="keyword">size_t</span> s)</span> <span class="title">noexcept</span><span class="params">(<span class="literal">true</span>)</span> </span>&#123;</span><br><span class="line">  v.resize(s); <span class="comment">// May throw</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码声明了函数f()不会抛出任何异常的规范，但是vector::reszie函数就可能在内存不够的时候无法分配导致抛出异常，所以该段代码会导致程序不正常终止，应该改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstddef&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;vector&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">(<span class="built_in">std</span>::<span class="built_in">vector</span>&lt;<span class="keyword">int</span>&gt; &amp;v, <span class="keyword">size_t</span> s)</span> </span>&#123;</span><br><span class="line">  v.resize(s); <span class="comment">// May throw, but that is okay</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码移除了动态异常规范，默认情况下，该函数允许任何异常被抛出。</p>
<p>下面来谈点C++编译器产商对于异常的外延:</p>
<p>一般来说，各个C++编译器产商都会加入自己的语言扩展来支持“指定一个函数抛不抛异常”，比如，Visual Studio就提供了 __declspec(nothrow)，Clang也支持 __attribute__((nothrow))的形式。但是这些产商都没有文档化如果违反这些扩展的异常规范会发生什么行为，我们姑且可以认为是未定义行为。</p>
<h3 id="ERR56-CPP-保证异常安全"><a href="#ERR56-CPP-保证异常安全" class="headerlink" title="ERR56-CPP. 保证异常安全"></a>ERR56-CPP. 保证异常安全</h3><blockquote>
<p><em>这里提下我本人的观点，C++大型项目和基础设施中，要满足保证这个条款正确实行太艰难了，所以Google C++ Coding Style才会一律禁止使用C++异常。所以以下内容更多的是作为参考</em></p>
</blockquote>
<p>严重程度: 高。如果代码不是异常安全的，那么一般情况下是导致资源泄漏，导致程序处于一个不一致，未知的状态，最终在程序运行在某个时间点上发生未定义行为，代码在第一个没保证异常安全的异常抛出后，运行了几天，甚至几年以后可能才发生未定义行为或者崩溃</p>
<p>恰当的处理错误和异常对于一个连续运行的正确的程序是至关重要的，而用C++提供的异常机制来报告错误也比返回错误码的方式要方面简洁。连C++的标准库都大量采用了异常来报错。</p>
<p>因为异常是打断了程序的执行路径，所以很容易导致资源泄漏，还有程序的状态出错，然而，代码为了避免这样的无法预料的情况就叫异常安全。</p>
<h4 id="代码样例对比-8"><a href="#代码样例对比-8" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstring&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">IntArray</span> &#123;</span></span><br><span class="line">  <span class="keyword">int</span> *<span class="built_in">array</span>;</span><br><span class="line">  <span class="built_in">std</span>::<span class="keyword">size_t</span> nElems;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">  ~IntArray() &#123;</span><br><span class="line">    <span class="keyword">delete</span>[] <span class="built_in">array</span>;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  IntArray(<span class="keyword">const</span> IntArray&amp; that); <span class="comment">// nontrivial copy constructor</span></span><br><span class="line">  IntArray&amp; <span class="keyword">operator</span>=(<span class="keyword">const</span> IntArray &amp;rhs) &#123;</span><br><span class="line">    <span class="keyword">if</span> (<span class="keyword">this</span> != &amp;rhs) &#123;</span><br><span class="line">      <span class="keyword">delete</span>[] <span class="built_in">array</span>;</span><br><span class="line">      <span class="built_in">array</span> = <span class="literal">nullptr</span>;</span><br><span class="line">      nElems = rhs.nElems;</span><br><span class="line">      <span class="keyword">if</span> (nElems) &#123;</span><br><span class="line">        <span class="built_in">array</span> = <span class="keyword">new</span> <span class="keyword">int</span>[nElems];</span><br><span class="line">        <span class="built_in">std</span>::<span class="built_in">memcpy</span>(<span class="built_in">array</span>, rhs.<span class="built_in">array</span>, nElems * <span class="keyword">sizeof</span>(*<span class="built_in">array</span>));</span><br><span class="line">      &#125;</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">return</span> *<span class="keyword">this</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码自定义了一个int类型的数组类，问题就出现在拷贝赋值函数中，如果内存不够，导致new分配符抛出异常那么后续的操作将不会被执行，这时候成员变量nElems已经在new之前被赋值了，有了状态，但是异常发生了，该状态无效。那么这个IntArray的对象将处于一个未知的状态，如果还在该对象上操作，或者该对象析构，就会导致未定义行为。所以可想而知，保证异常安全举步维艰，按理来说，以上的代码在项目中经常会出现的，开发人员很难发现问题，但是却不是无懈可击的代码，经过充分考虑后就是要保证异常发生后，对象还处于安全的状态:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;cstring&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">IntArray</span> &#123;</span></span><br><span class="line">  <span class="keyword">int</span> *<span class="built_in">array</span>;</span><br><span class="line">  <span class="built_in">std</span>::<span class="keyword">size_t</span> nElems;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">  ~IntArray() &#123;</span><br><span class="line">    <span class="keyword">delete</span>[] <span class="built_in">array</span>;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  IntArray(<span class="keyword">const</span> IntArray&amp; that); <span class="comment">// nontrivial copy constructor</span></span><br><span class="line">  IntArray&amp; <span class="keyword">operator</span>=(<span class="keyword">const</span> IntArray &amp;rhs) &#123;</span><br><span class="line">    <span class="keyword">int</span> *tmp(<span class="literal">nullptr</span>);</span><br><span class="line">    <span class="keyword">if</span>(rhs.nElems)&#123;</span><br><span class="line">      tmp = <span class="keyword">new</span> <span class="keyword">int</span>[rhs.nElems];</span><br><span class="line">      <span class="built_in">std</span>::<span class="built_in">memcpy</span>(tmp,rhs.<span class="built_in">array</span>,rhs.nElems * <span class="keyword">sizeof</span>(*<span class="built_in">array</span>));</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">delete</span> [] <span class="built_in">array</span>;</span><br><span class="line">    <span class="built_in">array</span> = tmp;</span><br><span class="line">    nElems = rhs.nElems;</span><br><span class="line">    <span class="keyword">return</span> *<span class="keyword">this</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>仔细分析以上代码，在异常安全上已经无懈可击了，当new分配失败，异常抛出，却没有影响此刻IntArray类型对象的自身的状态，等到分配完毕和拷贝数据到局部指针tmp分配的内存空间完毕，万事俱备只欠东风的时候，再来修改IntArray类型对象自身的状态，包括释放当前对象的数组空间，把指针指向tmp所分配的空间，然后再是设置当前对象的数组元素的个数，然后返回当前对象。</p>
<h3 id="ERR57-CPP-当处理异常的时候不要泄漏资源"><a href="#ERR57-CPP-当处理异常的时候不要泄漏资源" class="headerlink" title="ERR57-CPP. 当处理异常的时候不要泄漏资源"></a>ERR57-CPP. 当处理异常的时候不要泄漏资源</h3><p>严重程度: 低。内存和资源泄漏一般会最终会导致程序崩溃，如果攻击者通过特殊手段制造会导致资源泄漏的异常抛出，那么会导致程序反复泄漏资源内存，攻击者就可以制造拒绝服务攻击了。</p>
<p>这个在ERR56-CPP规范中也有支出，其实是两个规范是有相交兼容的地方。为了防止资源泄漏，所以要经常利用C++的RAII设计模式，当对象退出作用域，自动释放资源。</p>
<p>然而，构造函数就不提供这样的保护。因为构造函数的设计目地本来就包含资源的分配，如果它提前结束，也不会自动释放任何资源，C++标准[except.ctor]有如下声明:</p>
<blockquote>
<p>An object of any storage duration whose initialization or destruction is terminated by an exception will have destructors executed for all of its fully constructed subobjects (excluding the variant members of a union-like class), that is, for subobjects for which the principal constructor (12.6.2) has completed execution and the destructor has not yet begun execution. Similarly, if the non-delegating constructor for an object has completed execution and a delegating constructor for that object exits with an exception, the object’s destructor will be invoked. If the object was allocated in a new-expression, the matching deallocation function (3.7.4.2, 5.3.4, 12.5), if any, is called to free the storage occupied by the object.</p>
</blockquote>
<p>所以在C++编程中一般推荐在构造函数发生错误时用抛异常的方式来报错，抛异常千万不要导致资源泄漏，包括在对象构造阶段，这个与MEM51-CPP规范兼容。</p>
<h4 id="代码样例对比-9"><a href="#代码样例对比-9" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;new&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">SomeType</span> &#123;</span></span><br><span class="line">  SomeType() <span class="keyword">noexcept</span>; <span class="comment">// Performs nontrivial initialization.</span></span><br><span class="line">  ~SomeType(); <span class="comment">// Performs nontrivial finalization.</span></span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">process_item</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  SomeType *pst = <span class="keyword">new</span> (<span class="built_in">std</span>::nothrow) SomeType();</span><br><span class="line">  <span class="keyword">if</span> (!pst) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">    <span class="keyword">return</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    pst-&gt;process_item();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Process error, but do not recover from it; rethrow.</span></span><br><span class="line">    <span class="keyword">throw</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">delete</span> pst;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码很显然，在处理process_item()抛出的异常的时候，忘记释放pst已经分配好的内存资源了，导致了资源泄漏。所以很好改:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;new&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">SomeType</span> &#123;</span></span><br><span class="line">  SomeType() <span class="keyword">noexcept</span>; <span class="comment">// Performs nontrivial initialization.</span></span><br><span class="line">  ~SomeType(); <span class="comment">// Performs nontrivial finalization.</span></span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">process_item</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  SomeType *pst = <span class="keyword">new</span> (<span class="built_in">std</span>::nothrow) SomeType();</span><br><span class="line">  <span class="keyword">if</span> (!pst) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">    <span class="keyword">return</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    pst-&gt;process_item();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Process error, but do not recover from it; rethrow.</span></span><br><span class="line">    <span class="keyword">delete</span> pst;</span><br><span class="line">    <span class="keyword">throw</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">delete</span> pst;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>当然以上代码也不是没有缺点，缺点就是当要处理的异常种类增加的时候，那么每个catch块都会要写delete ptr来清除释放资源，而且还要保证清楚释放资源的操作不能抛出异常，不然又打破规范了。所以最好使用RAII机制:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">SomeType</span> &#123;</span></span><br><span class="line">  SomeType() <span class="keyword">noexcept</span>; <span class="comment">// Performs nontrivial initialization.</span></span><br><span class="line">  ~SomeType(); <span class="comment">// Performs nontrivial finalization.</span></span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">process_item</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  SomeType st;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    st.process_item();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Process error, but do not recover from it; rethrow.</span></span><br><span class="line">    <span class="keyword">throw</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="comment">// After re-throwing the exception, the</span></span><br><span class="line">  <span class="comment">// destructor is run for st.</span></span><br><span class="line">&#125;</span><br><span class="line"><span class="comment">// If f() exits without throwing an exception,</span></span><br><span class="line"><span class="comment">// the destructor is run for st.</span></span><br></pre></td></tr></table></figure>
<p>以上代码代码的好处就是不会遇到new分配失败的异常了，而且无论f()函数是通过throw退出，还是正常退出，对象st都会自动调用析构函数及时释放资源。</p>
<h4 id="代码样例对比-10"><a href="#代码样例对比-10" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">A</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">B</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">C</span> &#123;</span></span><br><span class="line">  A *a;</span><br><span class="line">  B *b;</span><br><span class="line"><span class="keyword">protected</span>:</span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">init</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  C() : a(<span class="keyword">new</span> A()), b(<span class="keyword">new</span> B()) &#123;</span><br><span class="line">    init();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码问题严重，new A和new B都可能抛出异常，如果new B抛出异常，导致构造函数异常，那么对象的析构函数也不会调用，这就导致了new A不能释放，资源泄漏。如果是init()发生异常，那么new A和new B都会泄漏。所以应该改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">A</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">B</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">C</span> &#123;</span></span><br><span class="line">  A *a;</span><br><span class="line">  B *b;</span><br><span class="line"><span class="keyword">protected</span>:</span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">init</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  C() : a(<span class="literal">nullptr</span>), b(<span class="literal">nullptr</span>) &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      a = <span class="keyword">new</span> A();</span><br><span class="line">      b = <span class="keyword">new</span> B();</span><br><span class="line">      init();</span><br><span class="line">    &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">      <span class="keyword">delete</span> a;</span><br><span class="line">      <span class="keyword">delete</span> b;</span><br><span class="line">      <span class="keyword">throw</span>;</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码就没有问题了，当抛出异常，都能及时释放资源，别惊奇，delete nullptr没有任何问题。但是上面代码虽然正确，但是不美观，可以利用智能指针这样的RAII机制简化代码:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;memory&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">A</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">B</span> &#123;</span><span class="comment">/* ... */</span>&#125;;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">C</span> &#123;</span></span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">unique_ptr</span>&lt;A&gt; a;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">unique_ptr</span>&lt;B&gt; b;</span><br><span class="line"><span class="keyword">protected</span>:</span><br><span class="line">  <span class="function"><span class="keyword">void</span> <span class="title">init</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  C() : a(<span class="keyword">new</span> A()), b(<span class="keyword">new</span> B()) &#123;</span><br><span class="line">    init();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br></pre></td></tr></table></figure>
<p>以上代码任何地方发生异常，std::unique_ptr对象一旦退出其作用域，就会调用析构函数释放资源。</p>
<h3 id="ERR58-CPP-在main函数开始执行之前处理所有的异常"><a href="#ERR58-CPP-在main函数开始执行之前处理所有的异常" class="headerlink" title="ERR58-CPP. 在main函数开始执行之前处理所有的异常"></a>ERR58-CPP. 在main函数开始执行之前处理所有的异常</h3><p>严重程度: 低。 如果异常没有被捕获，那么直接导致程序非正常终止，间接导致服务拒绝攻击。</p>
<p>不是所有的异常都能够被捕获，即使小心使用function-try-block这样的机制。C++标准[except.handle]有如下声明:</p>
<blockquote>
<p>Exceptions thrown in destructors of objects with static storage duration or in constructors of namespace scope objects with static storage duration are not caught by a functiontry-block on main() . Exceptions thrown in destructors of objects with thread storage duration or in constructors of namespace-scope objects with thread storage duration are not caught by a function-try-block on the initial function of the thread</p>
</blockquote>
<p>当声明一个静态对象或线程对象，而且没有在该对象上使用function-try-block这样的机制的时候，那么这个对象的类的构造函数必须声明为noexcept，必须遵守ERR55-CPP规范。另外如果没有捕获的异常在main函数开始前被抛出，或者main函数执行完毕后被抛出，那么没有任何的机会来处理异常，直接导致implementation-defined的行为，参考ERR50-CPP规范，另外，注意析构函数的异常规范，参考DCL57-CPP规范。</p>
<h4 id="代码样例对比-11"><a href="#代码样例对比-11" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">S</span> &#123;</span></span><br><span class="line">  S() <span class="keyword">noexcept</span>(<span class="literal">false</span>);</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="keyword">static</span> S globalS;</span><br></pre></td></tr></table></figure>
<p>以上的代码显然有问题，因为static类型的对象globalS是全局的，一定是在main函数开始执行就构造初始化了，但是这个类S的构造函数可能会抛出异常，如果异常发生，这个异常在main函数开始之前就被抛出了，开发者没有任何机会来catch这个异常，那么程序非正常终止。应该把代码改成以下:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">S</span> &#123;</span></span><br><span class="line">  S() <span class="keyword">noexcept</span>(<span class="literal">false</span>);</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function">S &amp;<span class="title">globalS</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">static</span> S s;</span><br><span class="line">    <span class="keyword">return</span> s;</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="comment">// Handle error, perhaps by logging it and gracefully terminating the application.</span></span><br><span class="line">  &#125;</span><br><span class="line"><span class="comment">// Unreachable.</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码对象s只会构造初始化一次，类似于单例模式，把对象s的初始化推迟到第一次调用globalS()函数，但是这样的方式让开发者有机会来catch处理异常了，这样就不会导致程序异常终止。</p>
<h4 id="代码样例对比-12"><a href="#代码样例对比-12" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="keyword">static</span> <span class="keyword">const</span> <span class="built_in">std</span>::<span class="function"><span class="built_in">string</span> <span class="title">global</span><span class="params">(<span class="string">"..."</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span></span></span><br><span class="line"><span class="function">  <span class="keyword">try</span> </span>&#123;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span>(...) &#123;</span><br><span class="line">    <span class="comment">// IMPORTANT: Will not catch exceptions thrown</span></span><br><span class="line">    <span class="comment">// from the constructor of global</span></span><br><span class="line">  &#125;</span><br></pre></td></tr></table></figure>
<p>以上的代码在main函数上采用了function-try-block的机制，所以main函数没有自己的花括号。即使用这样完整的捕获方式还是有问题，因为global对象的构造函数还是会发生于main函数执行之前，一旦发生异常，没有任何方式捕获，导致runtime库自动间接调用std::terminate()，程序非正常终止。解决办法也是有:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">static</span> <span class="keyword">const</span> <span class="keyword">char</span> *global = <span class="string">"..."</span>;</span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line"><span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码直接用常量指针的方式实现常量字符串，这样就不会抛任何异常，有句话说的好，绕过异常安全问题，就是不使用异常。嗯，所以很理解Google的做法。如果坚持使用异常可以自定义一个string类:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="keyword">namespace</span> my &#123;</span><br><span class="line">  <span class="class"><span class="keyword">struct</span> <span class="title">string</span> :</span> <span class="built_in">std</span>::<span class="built_in">string</span> &#123;</span><br><span class="line">    <span class="function"><span class="keyword">explicit</span> <span class="title">string</span><span class="params">(<span class="keyword">const</span> <span class="keyword">char</span> *msg,<span class="keyword">const</span> <span class="built_in">std</span>::<span class="built_in">string</span>::allocator_type &amp;alloc=<span class="built_in">std</span>::<span class="built_in">string</span>::allocator_type&#123;&#125;)</span> <span class="keyword">noexcept</span></span></span><br><span class="line">    try : std::string(msg, alloc) &#123;&#125; catch(...) &#123;</span><br><span class="line">      <span class="function"><span class="keyword">extern</span> <span class="keyword">void</span> <span class="title">log_message</span><span class="params">(<span class="keyword">const</span> <span class="keyword">char</span> *)</span> <span class="keyword">noexcept</span></span>;</span><br><span class="line">      log_message(<span class="string">"std::string constructor threw an exception"</span>);</span><br><span class="line">      <span class="built_in">std</span>::terminate();</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125;;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">static</span> <span class="keyword">const</span> my::<span class="function"><span class="built_in">string</span> <span class="title">global</span><span class="params">(<span class="string">"..."</span>)</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line"><span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上的代码自定义了一个string类，并且在string类的构造函数上使用了function-try-block机制，如果构造发生异常，直接主动调用std::terminate()在main函数执行之前终止程序。因为在构造函数中的任何异常都不会逃逸到构造函数之外，所以构造函数标记上了noexcept，这样自定义的string类，就可以全局地声明static对象了，程序不会非正常终止了。</p>
<h4 id="代码样例对比-13"><a href="#代码样例对比-13" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">extern</span> <span class="keyword">int</span> <span class="title">f</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line"><span class="keyword">int</span> i = f();</span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line"><span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码变量i本质也是个全局变量，其初始化依赖f()函数并且在main函数执行前，所以一旦f()抛出异常，那么程序就非正常终止了。所以按照之前的思路改就可以。</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">f_helper</span><span class="params">()</span> <span class="keyword">noexcept</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="function"><span class="keyword">extern</span> <span class="keyword">int</span> <span class="title">f</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>;</span><br><span class="line">    <span class="keyword">return</span> f();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (...) &#123;</span><br><span class="line">    <span class="function"><span class="keyword">extern</span> <span class="keyword">void</span> <span class="title">log_message</span><span class="params">(<span class="keyword">const</span> <span class="keyword">char</span> *)</span> <span class="keyword">noexcept</span></span>;</span><br><span class="line">    log_message(<span class="string">"f() threw an exception"</span>);</span><br><span class="line">    <span class="built_in">std</span>::terminate();</span><br><span class="line">  &#125;</span><br><span class="line"><span class="comment">// Unreachable.</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">int</span> i = f_helper();</span><br><span class="line"><span class="function"><span class="keyword">int</span> <span class="title">main</span><span class="params">()</span> </span>&#123;</span><br><span class="line"><span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码在f()函数之上做了一个wrapper，在这个helper函数中catch住所有的异常，阻止异常往外逃逸，这样程序的终止就在掌控范围内了。</p>
<h3 id="ERR59-CPP-不要跨执行边界抛异常"><a href="#ERR59-CPP-不要跨执行边界抛异常" class="headerlink" title="ERR59-CPP. 不要跨执行边界抛异常"></a>ERR59-CPP. 不要跨执行边界抛异常</h3><p>严重程度： 高。跨执行边界抛异常导致的后果依赖于异常处理机制的实现细节，结果可有有多种，可能是正确的，可能直接就导致未定义行为。</p>
<p>如果动态库和可执行文件都是由同一个编译器的同一个版本编译的，那么跨边界抛异常可能是安全的，但是最好需要编译器设置一致的编译参数和链接参数，这样才有可能二进制兼容，跨执行边界抛异常才可能是安全的。</p>
<p>其实以上只是理想状态，为了代码复用，不可能每个动态库都是同一个编译器的同一个版本采用一致的参数来编译链接。而恰恰执行边界的界定就是两边可执行二进制文件是用不同的编译器编译的，这里的不同编译器，包括同产商的版本的不同，不同产商的编译器。</p>
<h4 id="代码样例对比-14"><a href="#代码样例对比-14" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// library.h</span></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span></span>; <span class="comment">// Implemented by the library maybe DLL or so,cannot be the static lib, cause static lib only be linked into exe file by same compilor</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// library.cpp</span></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">false</span>)</span> </span>&#123;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">  <span class="keyword">if</span> (<span class="comment">/* ... */</span>) &#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="number">42</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// application.cpp</span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">"library.h"</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    func();</span><br><span class="line">  &#125; <span class="keyword">catch</span>(<span class="keyword">int</span> &amp;e) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码可能由于ABI不兼容导致程序出错，其实也隐式兼容了EXP60-CPP规则。</p>
<p>说点以上代码在不同编译器实现上的情况:</p>
<p>如果库的代码library.cpp是用MinGW-w64上默认安装的GCC 4.9编译的(不含任何特殊的编译参数)，那么异常的抛出会依赖zero-cost，table-based的一种异常模型，该模型底层基于<a href="http://dwarfstd.org/" target="_blank" rel="noopener">DWARF调试标准</a>同时使用Itanium ABI。 如果应用可执行文件代码用Visual Studio 2013编译，那么catch代码handler块底层就是基于SEH异常处理机制还有使用Microsoft ABI。这两种异常处理格式不兼容，ABI也不兼容，最终导致程序非正常终止。特别是，这种情况下，catch代码块根本捕获不到异常，最终导致std::terminate()被间接调用。</p>
<p>所以代码应该改成以下，最好通过C语言接口的方式，以返回错误码的形式报错:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// library.h</span></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">true</span>)</span></span>; <span class="comment">// Implemented by the library maybe DLL or so,cannot be the static lib, cause static lib only be linked into exe file by same compilor</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// library.cpp</span></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">func</span><span class="params">()</span> <span class="title">noexcept</span><span class="params">(<span class="literal">true</span>)</span> </span>&#123;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">  <span class="keyword">if</span> (<span class="comment">/* ... */</span>) &#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="number">42</span>;</span><br><span class="line">  &#125;</span><br><span class="line">  <span class="keyword">return</span> <span class="number">0</span>;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// application.cpp</span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">"library.h"</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line"> </span><br><span class="line">  <span class="keyword">if</span>( <span class="keyword">int</span> err = func())</span><br><span class="line">  &#123;</span><br><span class="line">    <span class="comment">// Handle Error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码两边可执行体都采用同样的编译器同样的版本参数保持一致编译链接就可以了，异常处理机制和API都需要保证兼容。</p>
<h3 id="ERR60-CPP-异常对象不要以拷贝构造的形式抛出"><a href="#ERR60-CPP-异常对象不要以拷贝构造的形式抛出" class="headerlink" title="ERR60-CPP. 异常对象不要以拷贝构造的形式抛出"></a>ERR60-CPP. 异常对象不要以拷贝构造的形式抛出</h3><p>严重程度: 低。可能最终导致程序非正常终止，这样的间接后果就是资源泄漏，容易遭受拒绝服务攻击。</p>
<p>当一个异常被抛出的时候，异常对象是被throw操作符拷贝到一个临时对象中的，一般这个临时对象是用来初始化Handler的，C++标准[except.throw]有如下声明:</p>
<blockquote>
<p>Throwing an exception copy-initializes a temporary object, called the exception object. The temporary is an lvalue and is used to initialize the variable declared in the matching handler.</p>
</blockquote>
<p>也就是用这个临时对象来传入匹配的catch(Exception&amp; expObj)块的参数的。</p>
<p>因为异常对象是被拷贝到临时对象中的，所以会调用其拷贝构造函数来初始化临时对象，如果拷贝构造函数中又抛出了异常，那么C++ runtime库会自动调用std::terminate()，这个调用会导致未定义行为，这个与ERR50-CPP规范兼容。</p>
<p>所以异常对象的拷贝构造函数必须声明为noexcept，包括隐式定义的拷贝构造函数，如果声明了noexcept的函数还是抛出了异常那么就违背了ERR55-CPP规范。</p>
<h4 id="代码样例对比-15"><a href="#代码样例对比-15" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;string&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">S</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">string</span> m;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  S(<span class="keyword">const</span> <span class="keyword">char</span> *msg) : m(msg) &#123;&#125;</span><br><span class="line">  <span class="function"><span class="keyword">const</span> <span class="keyword">char</span> *<span class="title">what</span><span class="params">()</span> <span class="keyword">const</span> <span class="keyword">noexcept</span> override </span>&#123;</span><br><span class="line">    <span class="keyword">return</span> m.c_str();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">g</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="comment">// If some condition doesn't hold...</span></span><br><span class="line">  <span class="keyword">throw</span> S(<span class="string">"Condition did not hold"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    g();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (S &amp;s) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码可以看出，异常从g()中被抛出。然而异常类S有个成员对象std::string，而std::string的拷贝构造函数没有被声明为noexcept，而且异常类S的隐式定义(编译器默认生成)的构造函数也没有声明为noexcept，在低内存的场景下，std::string的拷贝构造函数可以由于无法分配足够的内存而导致抛出异常std::bad_alloc无法完成拷贝构造，间接导致了S的拷贝构造也抛出异常，异常对象构造失败，无法catch，程序非正常终止。</p>
<p>所以需要改成以下代码:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;stdexcept&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;type_traits&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">S</span> :</span> <span class="built_in">std</span>::runtime_error &#123;</span><br><span class="line">  S(<span class="keyword">const</span> <span class="keyword">char</span> *msg) : <span class="built_in">std</span>::runtime_error(msg) &#123;&#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="keyword">static_assert</span>(<span class="built_in">std</span>::is_nothrow_copy_constructible&lt;S&gt;::value,<span class="string">"S must be nothrow copy constructible"</span>);</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">g</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="comment">// If some condition doesn't hold...</span></span><br><span class="line">  <span class="keyword">throw</span> S(<span class="string">"Condition did not hold"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    g();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (S &amp;s) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码直接让异常类S继承了std::runtime_error类，使用runtime_error类保存异常信息，就弃用std::string来保存异常信息了，然后还用static_assert在编译时刻测试异常类S的拷贝构造函数不会抛出异常。或者不要继承std::runtime_error类，直接封装该类并继承std::exception类，这样最符合规范，少用继承，多用复合类的策略:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;stdexcept&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;type_traits&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">S</span> :</span> <span class="keyword">public</span> <span class="built_in">std</span>::exception &#123;</span><br><span class="line">  <span class="built_in">std</span>::runtime_error m;</span><br><span class="line"><span class="keyword">public</span>:</span><br><span class="line">  S(<span class="keyword">const</span> <span class="keyword">char</span> *msg) : m(msg) &#123;&#125;</span><br><span class="line">  <span class="function"><span class="keyword">const</span> <span class="keyword">char</span> *<span class="title">what</span><span class="params">()</span> <span class="keyword">const</span> <span class="keyword">noexcept</span> override </span>&#123;</span><br><span class="line">    <span class="keyword">return</span> m.what();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="keyword">static_assert</span>(<span class="built_in">std</span>::is_nothrow_copy_constructible&lt;S&gt;::value,<span class="string">"S must be nothrow copy constructible"</span>);</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">g</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="comment">// If some condition doesn't hold...</span></span><br><span class="line">  <span class="keyword">throw</span> S(<span class="string">"Condition did not hold"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    g();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (S &amp;s) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h3 id="ERR61-CPP-catch异常的时候以左值引用的方式捕获异常对象"><a href="#ERR61-CPP-catch异常的时候以左值引用的方式捕获异常对象" class="headerlink" title="ERR61-CPP. catch异常的时候以左值引用的方式捕获异常对象"></a>ERR61-CPP. catch异常的时候以左值引用的方式捕获异常对象</h3><p>严重程度: 低。对象分片直接导致程序不正常终止，这种情况，一般对于异常对象本身没什么问题，但是会导致未指定行为，该行为依赖于异常handler的处理方式。</p>
<p>当一个异常被抛出的时候，它被拷贝到一个临时匿名对象中，这个临时对象就叫异常对象，该异常对象会匹配“距离它最近”的catch代码块并传入进去，C++标准[except.handle]中有如下声明:</p>
<blockquote>
<p>The variable declared by the exception-declaration, of type cv T or cv T&amp;, is initialized from the exception object, of type E, as follows:</p>
</blockquote>
<blockquote>
<p>• if T is a base class of E, the variable is copy-initialized from the corresponding base class subobject of the exception object;</p>
</blockquote>
<blockquote>
<p>• otherwise, the variable is copy-initialized from the exception object.</p>
</blockquote>
<p>也就是说catch代码的输入参数可以是引用捕获，或者是值传递的捕获方式，但是值传递的话，又会调用临时异常对象的拷贝构造函数，极端情况会发生对象分片，因为异常对象是有继承关系的，这样会导致继承类的异常对象的完整状态通过值赋值拷贝的方式发生信息丢失，导致不可恢复的错误，需要遵守OOP51-CPP规范，而且以值传递会调用临时异常对象的拷贝构造函数，万一其拷贝构造函数发生异常，那么程序又非正常终止了，这样违背了ERR60-CPP规范了。</p>
<p>所以总应该以左值引用捕获异常对象，除非异常类的类型是trivial type的。C++标准[basic.types]对trivial types作出了如下声明:</p>
<blockquote>
<p>Arithmetic types, enumeration types, pointer types, pointer to member types,std::nullptr_t, and cv-qualified versions of these types are collectively called scalar types…. Scalar types, trivial class types, arrays of such types and cv-qualified versions of these types are collectively called trivial types.</p>
</blockquote>
<p>C++标准[class]还定义了trivial class types是什么:</p>
<blockquote>
<p>A trivially copyable class is a class that:</p>
</blockquote>
<blockquote>
<p>• has no non-trivial copy constructors,</p>
</blockquote>
<blockquote>
<p>• has no non-trivial move constructors,</p>
</blockquote>
<blockquote>
<p>• has no non-trivial copy assignment operators,</p>
</blockquote>
<blockquote>
<p>• has no non-trivial move assignment operators, and</p>
</blockquote>
<blockquote>
<p>• has a trivial destructor.</p>
</blockquote>
<blockquote>
<p>A trivial class is a class that has a default constructor, has no non-trivial default constructors, and is trivially copyable. [Note: In particular, a trivially copyable or trivial class does not have virtual functions or virtual base classes. — end note]</p>
</blockquote>
<h4 id="代码样例对比-16"><a href="#代码样例对比-16" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">S</span> :</span> <span class="built_in">std</span>::exception &#123;</span><br><span class="line">  <span class="function"><span class="keyword">const</span> <span class="keyword">char</span> *<span class="title">what</span><span class="params">()</span> <span class="keyword">const</span> <span class="keyword">noexcept</span> override </span>&#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="string">"My custom exception"</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">throw</span> S();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (<span class="built_in">std</span>::exception e) &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; e.what() &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码以传值的方式捕获异常对象，所以可能导致异常对象拷贝初始化对象e的时候被分片，先拷贝的std::exception 后拷贝异常类S，导致开发者无法预料的输出(implementation-defined)，可能不会输出”My custom exception”， 而是直接调用std::exception::what()。所以为了防止这样，应该改为引用捕获:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;exception&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">struct</span> <span class="title">S</span> :</span> <span class="built_in">std</span>::exception &#123;</span><br><span class="line">  <span class="function"><span class="keyword">const</span> <span class="keyword">char</span> *<span class="title">what</span><span class="params">()</span> <span class="keyword">const</span> <span class="keyword">noexcept</span> override </span>&#123;</span><br><span class="line">    <span class="keyword">return</span> <span class="string">"My custom exception"</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">throw</span> S();</span><br><span class="line">  &#125; <span class="keyword">catch</span> (<span class="built_in">std</span>::exception &amp;e) &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cout</span> &lt;&lt; e.what() &lt;&lt; <span class="built_in">std</span>::<span class="built_in">endl</span>;</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码永远始终会调用S::what()了。</p>
<h3 id="ERR62-CPP-当把字符串转换成一个数值时，注意检测异常"><a href="#ERR62-CPP-当把字符串转换成一个数值时，注意检测异常" class="headerlink" title="ERR62-CPP. 当把字符串转换成一个数值时，注意检测异常"></a>ERR62-CPP. 当把字符串转换成一个数值时，注意检测异常</h3><p>严重程度: 中等。内存数据可能会冲突，导致非法代码被植入。</p>
<p>由字符串转换为一个数值时，这个过程中可能会发生很多错误异常，比如字符串根本就不是一个数值，或者字符串表示的数值已经超出int或者float，double所表示的范围了，可能字符串除了数值里面还包含一些非法的字符，其中都可能导致转换失败。</p>
<h4 id="代码样例对比-17"><a href="#代码样例对比-17" class="headerlink" title="代码样例对比"></a>代码样例对比</h4><figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">int</span> i, j;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cin</span> &gt;&gt; i &gt;&gt; j;</span><br><span class="line">  <span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上代码本质就是从输入流获取的字符串转换成了多个int类型的值，问题就出在从输入流获取的字符串是不可预料的，一旦int类型不能表示，或超出表示范围，你就无法预测了。很好改:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">int</span> i, j;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cin</span>.exceptions(<span class="built_in">std</span>::istream::failbit |</span><br><span class="line">  <span class="built_in">std</span>::istream::badbit);</span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cin</span> &gt;&gt; i &gt;&gt; j;</span><br><span class="line">    <span class="comment">// ...</span></span><br><span class="line">  &#125; <span class="keyword">catch</span> (<span class="built_in">std</span>::istream::failure &amp;E) &#123;</span><br><span class="line">    <span class="comment">// Handle error</span></span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>以上可以对std::cin设置检测的异常，转换过程如果失败，就立刻抛出异常。还可以向以下这么改:</p>
<figure class="highlight cpp"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;iostream&gt;</span></span></span><br><span class="line"><span class="meta">#<span class="meta-keyword">include</span> <span class="meta-string">&lt;limits&gt;</span></span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">void</span> <span class="title">f</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">int</span> i;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cin</span> &gt;&gt; i;</span><br><span class="line">  <span class="keyword">if</span> (<span class="built_in">std</span>::<span class="built_in">cin</span>.fail()) &#123;</span><br><span class="line">    <span class="comment">// Handle failure to convert the value.</span></span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cin</span>.clear();</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cin</span>.ignore(</span><br><span class="line">    <span class="built_in">std</span>::numeric_limits&lt;<span class="built_in">std</span>::streamsize&gt;::max(), <span class="string">' '</span>);</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  <span class="keyword">int</span> j;</span><br><span class="line">  <span class="built_in">std</span>::<span class="built_in">cin</span> &gt;&gt; j;</span><br><span class="line">  <span class="keyword">if</span> (<span class="built_in">std</span>::<span class="built_in">cin</span>.fail()) &#123;</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cin</span>.clear();</span><br><span class="line">    <span class="built_in">std</span>::<span class="built_in">cin</span>.ignore(</span><br><span class="line">    <span class="built_in">std</span>::numeric_limits&lt;<span class="built_in">std</span>::streamsize&gt;::max(), <span class="string">' '</span>);</span><br><span class="line">  &#125;</span><br><span class="line"><span class="comment">// ...</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

      
    </div>
    <footer class="article-footer">
      <a data-url="https://alexiachen.github.io/blog/2017/08/09/cert-cpp-seven/" data-id="cjtctb4ko009t8rqfb9ggwncx" class="article-share-link">Share</a>
      
      
  <ul class="article-tag-list"><li class="article-tag-list-item"><a class="article-tag-list-link" href="/blog/tags/C-C/">C/C++</a></li><li class="article-tag-list-item"><a class="article-tag-list-link" href="/blog/tags/CERT/">CERT</a></li></ul>

    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/blog/2017/08/11/cert-cpp-eight/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Newer</strong>
      <div class="article-nav-title">
        
          CERT C++编码规范翻译（OOP）
        
      </div>
    </a>
  
  
    <a href="/blog/2017/08/09/cert-cpp-six/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Older</strong>
      <div class="article-nav-title">CERT C++编码规范翻译(FIO)</div>
    </a>
  
</nav>

  
</article>

</section>
        
          <aside id="sidebar">
  
    

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Tag Cloud</h3>
    <div class="widget tagcloud">
      <a href="/blog/tags/Bloom-Filter/" style="font-size: 10px;">Bloom Filter</a> <a href="/blog/tags/C-C/" style="font-size: 20px;">C/C++</a> <a href="/blog/tags/CERT/" style="font-size: 18.33px;">CERT</a> <a href="/blog/tags/CMake/" style="font-size: 10px;">CMake</a> <a href="/blog/tags/DLL/" style="font-size: 10px;">DLL</a> <a href="/blog/tags/DNS/" style="font-size: 10px;">DNS</a> <a href="/blog/tags/IM/" style="font-size: 13.33px;">IM</a> <a href="/blog/tags/IO/" style="font-size: 10px;">IO</a> <a href="/blog/tags/Java/" style="font-size: 10px;">Java</a> <a href="/blog/tags/Linux/" style="font-size: 13.33px;">Linux</a> <a href="/blog/tags/MySQL/" style="font-size: 10px;">MySQL</a> <a href="/blog/tags/Oracle/" style="font-size: 10px;">Oracle</a> <a href="/blog/tags/Qos/" style="font-size: 11.67px;">Qos</a> <a href="/blog/tags/RFB协议/" style="font-size: 10px;">RFB协议</a> <a href="/blog/tags/SQLite/" style="font-size: 10px;">SQLite</a> <a href="/blog/tags/Scala/" style="font-size: 10px;">Scala</a> <a href="/blog/tags/TCP-IP/" style="font-size: 10px;">TCP/IP</a> <a href="/blog/tags/VNC协议/" style="font-size: 10px;">VNC协议</a> <a href="/blog/tags/Visual-Studio/" style="font-size: 10px;">Visual Studio</a> <a href="/blog/tags/Win32/" style="font-size: 13.33px;">Win32</a> <a href="/blog/tags/Y组合子/" style="font-size: 10px;">Y组合子</a> <a href="/blog/tags/bat/" style="font-size: 10px;">bat</a> <a href="/blog/tags/ioccc/" style="font-size: 10px;">ioccc</a> <a href="/blog/tags/lambda演算/" style="font-size: 10px;">lambda演算</a> <a href="/blog/tags/windows/" style="font-size: 11.67px;">windows</a> <a href="/blog/tags/上下文无关文法/" style="font-size: 10px;">上下文无关文法</a> <a href="/blog/tags/事业/" style="font-size: 10px;">事业</a> <a href="/blog/tags/互联网/" style="font-size: 10px;">互联网</a> <a href="/blog/tags/人生/" style="font-size: 10px;">人生</a> <a href="/blog/tags/传统行业/" style="font-size: 10px;">传统行业</a> <a href="/blog/tags/信息安全/" style="font-size: 10px;">信息安全</a> <a href="/blog/tags/内存模型/" style="font-size: 10px;">内存模型</a> <a href="/blog/tags/函数式编程/" style="font-size: 11.67px;">函数式编程</a> <a href="/blog/tags/单例模式/" style="font-size: 10px;">单例模式</a> <a href="/blog/tags/双向链表/" style="font-size: 10px;">双向链表</a> <a href="/blog/tags/可计算性/" style="font-size: 10px;">可计算性</a> <a href="/blog/tags/同步异步/" style="font-size: 10px;">同步异步</a> <a href="/blog/tags/团队管理/" style="font-size: 11.67px;">团队管理</a> <a href="/blog/tags/多核编程/" style="font-size: 10px;">多核编程</a> <a href="/blog/tags/多线程编程/" style="font-size: 10px;">多线程编程</a> <a href="/blog/tags/天体物理/" style="font-size: 10px;">天体物理</a> <a href="/blog/tags/套路/" style="font-size: 10px;">套路</a> <a href="/blog/tags/学术/" style="font-size: 10px;">学术</a> <a href="/blog/tags/宇宙学/" style="font-size: 10px;">宇宙学</a> <a href="/blog/tags/性能优化/" style="font-size: 10px;">性能优化</a> <a href="/blog/tags/技术/" style="font-size: 10px;">技术</a> <a href="/blog/tags/指令重排序/" style="font-size: 10px;">指令重排序</a> <a href="/blog/tags/操作系统/" style="font-size: 10px;">操作系统</a> <a href="/blog/tags/敏捷开发/" style="font-size: 10px;">敏捷开发</a> <a href="/blog/tags/数据压缩/" style="font-size: 10px;">数据压缩</a> <a href="/blog/tags/数据库/" style="font-size: 10px;">数据库</a> <a href="/blog/tags/数据恢复/" style="font-size: 10px;">数据恢复</a> <a href="/blog/tags/数据结构与算法/" style="font-size: 11.67px;">数据结构与算法</a> <a href="/blog/tags/旅行/" style="font-size: 10px;">旅行</a> <a href="/blog/tags/无线网卡/" style="font-size: 10px;">无线网卡</a> <a href="/blog/tags/有限自动机/" style="font-size: 10px;">有限自动机</a> <a href="/blog/tags/构建工具/" style="font-size: 10px;">构建工具</a> <a href="/blog/tags/模板元编程/" style="font-size: 10px;">模板元编程</a> <a href="/blog/tags/民主/" style="font-size: 11.67px;">民主</a> <a href="/blog/tags/汇编语言/" style="font-size: 10px;">汇编语言</a> <a href="/blog/tags/消息推送/" style="font-size: 10px;">消息推送</a> <a href="/blog/tags/混乱代码/" style="font-size: 10px;">混乱代码</a> <a href="/blog/tags/物联网/" style="font-size: 10px;">物联网</a> <a href="/blog/tags/猎人/" style="font-size: 10px;">猎人</a> <a href="/blog/tags/理想/" style="font-size: 10px;">理想</a> <a href="/blog/tags/理论计算机/" style="font-size: 10px;">理论计算机</a> <a href="/blog/tags/生活/" style="font-size: 13.33px;">生活</a> <a href="/blog/tags/研究/" style="font-size: 10px;">研究</a> <a href="/blog/tags/程序语言理论/" style="font-size: 15px;">程序语言理论</a> <a href="/blog/tags/类型系统/" style="font-size: 10px;">类型系统</a> <a href="/blog/tags/线程/" style="font-size: 10px;">线程</a> <a href="/blog/tags/线程安全/" style="font-size: 10px;">线程安全</a> <a href="/blog/tags/缓存/" style="font-size: 10px;">缓存</a> <a href="/blog/tags/编程范式/" style="font-size: 10px;">编程范式</a> <a href="/blog/tags/编程语言/" style="font-size: 10px;">编程语言</a> <a href="/blog/tags/编译原理/" style="font-size: 11.67px;">编译原理</a> <a href="/blog/tags/美国/" style="font-size: 10px;">美国</a> <a href="/blog/tags/职业生涯/" style="font-size: 10px;">职业生涯</a> <a href="/blog/tags/自然语言处理/" style="font-size: 10px;">自然语言处理</a> <a href="/blog/tags/自由/" style="font-size: 11.67px;">自由</a> <a href="/blog/tags/英语/" style="font-size: 10px;">英语</a> <a href="/blog/tags/装修/" style="font-size: 10px;">装修</a> <a href="/blog/tags/计算机体系结构/" style="font-size: 10px;">计算机体系结构</a> <a href="/blog/tags/计算机科学/" style="font-size: 10px;">计算机科学</a> <a href="/blog/tags/计算机网络/" style="font-size: 11.67px;">计算机网络</a> <a href="/blog/tags/计算理论/" style="font-size: 11.67px;">计算理论</a> <a href="/blog/tags/词法分析/" style="font-size: 10px;">词法分析</a> <a href="/blog/tags/诗歌/" style="font-size: 10px;">诗歌</a> <a href="/blog/tags/语义学/" style="font-size: 10px;">语义学</a> <a href="/blog/tags/调试/" style="font-size: 11.67px;">调试</a> <a href="/blog/tags/软件工程/" style="font-size: 16.67px;">软件工程</a> <a href="/blog/tags/软件开发/" style="font-size: 10px;">软件开发</a> <a href="/blog/tags/软件调试/" style="font-size: 10px;">软件调试</a> <a href="/blog/tags/远程桌面/" style="font-size: 10px;">远程桌面</a> <a href="/blog/tags/逻辑/" style="font-size: 11.67px;">逻辑</a> <a href="/blog/tags/重构/" style="font-size: 10px;">重构</a> <a href="/blog/tags/错误处理/" style="font-size: 10px;">错误处理</a> <a href="/blog/tags/闭包/" style="font-size: 10px;">闭包</a> <a href="/blog/tags/阻塞非阻塞/" style="font-size: 10px;">阻塞非阻塞</a> <a href="/blog/tags/项目管理/" style="font-size: 11.67px;">项目管理</a> <a href="/blog/tags/马尔科夫链/" style="font-size: 10px;">马尔科夫链</a> <a href="/blog/tags/驱动开发/" style="font-size: 10px;">驱动开发</a> <a href="/blog/tags/黑洞/" style="font-size: 10px;">黑洞</a>
    </div>
  </div>

  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Archives</h3>
    <div class="widget">
      <ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2019/03/">March 2019</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/12/">December 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/11/">November 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/10/">October 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/08/">August 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/06/">June 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/04/">April 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/03/">March 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2018/02/">February 2018</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/12/">December 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/11/">November 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/10/">October 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/09/">September 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/08/">August 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/07/">July 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/06/">June 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/05/">May 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/03/">March 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2017/02/">February 2017</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/10/">October 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/09/">September 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/08/">August 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/07/">July 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/05/">May 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/04/">April 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/02/">February 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2016/01/">January 2016</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2015/11/">November 2015</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/11/">November 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/09/">September 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/08/">August 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/07/">July 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/06/">June 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/05/">May 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/03/">March 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2014/02/">February 2014</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2013/07/">July 2013</a></li><li class="archive-list-item"><a class="archive-list-link" href="/blog/archives/2013/06/">June 2013</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">Recent Posts</h3>
    <div class="widget">
      <ul>
        
          <li>
            <a href="/blog/2019/03/17/bloom-filter/">实现一个简单的高性能布隆过滤器</a>
          </li>
        
          <li>
            <a href="/blog/2019/03/10/auto-complete-markov-chain/">用马尔科夫链来做自动补全</a>
          </li>
        
          <li>
            <a href="/blog/2018/12/15/manjaro-rtl8821ce/">manjaro下安装配置无线网卡驱动</a>
          </li>
        
          <li>
            <a href="/blog/2018/11/11/cpp-closure/">C++的闭包</a>
          </li>
        
          <li>
            <a href="/blog/2018/10/15/finite-automaton/">最简单的计算机之有限自动机</a>
          </li>
        
      </ul>
    </div>
  </div>

  
</aside>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2019 MathxH Chen<br>
      Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>
    </div>
  </div>
</footer>
    </div>
    <nav id="mobile-nav">
  
    <a href="/blog/" class="mobile-nav-link">Home</a>
  
    <a href="/blog/archives" class="mobile-nav-link">Archives</a>
  
    <a href="/blog/about" class="mobile-nav-link">About</a>
  
    <a href="/blog/resume" class="mobile-nav-link">Resume</a>
  
</nav>
    

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


  <link rel="stylesheet" href="/blog/fancybox/jquery.fancybox.css">
  <script src="/blog/fancybox/jquery.fancybox.pack.js"></script>


<script src="/blog/js/script.js"></script>



  </div>
</body>
</html>